name: Build and Release on main
permissions: write-all

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build JAR file
        run: mvn clean package
        
      - name: Build clientApp JAR
        run: mvn -f clientApp/pom.xml package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.pull_request.head.ref }}
          release_name: ${{ github.event.pull_request.head.ref }}
          body: |
            Changes in this release:
            - Added new features
            - Fixed bugs
          draft: false
          prerelease: false

      - name: Upload JAR file
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/book-review-listing-1.0-SNAPSHOT.jar
          asset_name: book-review-listing-1.0-SNAPSHOT.jar
          asset_content_type: application/java-archive
      
      - name: Upload clientApp JAR
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: clientApp/target/book-review-listing-client-1.0-SNAPSHOT.jar
          asset_name: book-review-listing-client-1.0-SNAPSHOT.jar
          asset_content_type: application/java-archive

